
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '3745226AC15596D5A53B765228F9BE36'
    
_lr_action_items = {'TYPEBOOL':([6,],[9,]),'TYPESTRING':([6,],[10,]),'TYPEINT':([6,],[11,]),'PROGRAMA':([0,],[2,]),'VAR':([3,13,],[6,6,]),'COLON':([8,9,10,11,12,],[13,-9,-10,-7,-8,]),'TYPEFLOAT':([6,],[12,]),'ID':([2,],[3,]),'$end':([1,3,4,5,7,13,14,15,16,],[0,-11,-2,-1,-3,-11,-5,-4,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'tipo':([6,],[8,]),'vars':([3,13,],[4,14,]),'vars_opt':([3,],[5,]),'programa':([0,],[1,]),'vars_loop':([13,],[15,]),'empty':([3,13,],[7,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> PROGRAMA ID vars_opt','programa',3,'p_programa','frida_parser.py',17),
  ('vars_opt -> vars','vars_opt',1,'p_vars_opt','frida_parser.py',22),
  ('vars_opt -> empty','vars_opt',1,'p_vars_opt','frida_parser.py',23),
  ('vars -> VAR tipo COLON vars_loop','vars',4,'p_vars','frida_parser.py',30),
  ('vars_loop -> vars','vars_loop',1,'p_vars_loop','frida_parser.py',33),
  ('vars_loop -> empty','vars_loop',1,'p_vars_loop','frida_parser.py',34),
  ('tipo -> TYPEINT','tipo',1,'p_tipo','frida_parser.py',39),
  ('tipo -> TYPEFLOAT','tipo',1,'p_tipo','frida_parser.py',40),
  ('tipo -> TYPEBOOL','tipo',1,'p_tipo','frida_parser.py',41),
  ('tipo -> TYPESTRING','tipo',1,'p_tipo','frida_parser.py',42),
  ('empty -> <empty>','empty',0,'p_empty','frida_parser.py',45),
]
